Repository goorm-369/893-back, pull requests merged in 2025-06, with the labels that each got.

#156 Refactor: 경매 상품 관련 에러 핸들링 및 리팩토링
  src/main/java/com/samyookgoo/palgoosam/auction/dto/response/AuctionCreateResponse.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/response/CategoryResponse.java
  src/main/java/com/samyookgoo/palgoosam/auction/exception/AuctionCategoryException.java
  src/main/java/com/samyookgoo/palgoosam/auction/exception/AuctionForbiddenException.java
  src/main/java/com/samyookgoo/palgoosam/auction/exception/AuctionImageException.java
  src/main/java/com/samyookgoo/palgoosam/auction/exception/AuctionInvalidStateException.java
  src/main/java/com/samyookgoo/palgoosam/auction/exception/AuctionUpdateLockedException.java
  src/main/java/com/samyookgoo/palgoosam/auction/exception/CategoryNotFoundException.java
  src/main/java/com/samyookgoo/palgoosam/auction/service/AuctionService.java
  src/main/java/com/samyookgoo/palgoosam/global/exception/ErrorCode.java
  src/main/java/com/samyookgoo/palgoosam/payment/exception/PaymentNotFoundException.java
Labels: Feature, Refactor, Backend

#165 Test: BidService, BidRepository 테스트 작성 및 리팩토링
  src/main/java/com/samyookgoo/palgoosam/auction/domain/Auction.java
  src/main/java/com/samyookgoo/palgoosam/bid/controller/BidController.java
  src/main/java/com/samyookgoo/palgoosam/bid/controller/response/BidOverviewResponse.java
  src/main/java/com/samyookgoo/palgoosam/bid/domain/Bid.java
  src/main/java/com/samyookgoo/palgoosam/bid/repository/BidRepository.java
  src/main/java/com/samyookgoo/palgoosam/bid/service/BidService.java
  src/main/java/com/samyookgoo/palgoosam/bid/service/response/BidStatsResponse.java
  src/main/java/com/samyookgoo/palgoosam/global/exception/ErrorCode.java
  src/main/java/com/samyookgoo/palgoosam/payment/controller/PaymentController.java
  src/test/java/com/samyookgoo/palgoosam/bid/repository/BidRepositoryTest.java
  src/test/java/com/samyookgoo/palgoosam/bid/service/BidServiceTest.java
Labels: Test, Backend

#168 Chore: 빌더 기본값 및 타입 안정성 보완 + 테스트 및 Jacoco 환경 개선
  build.gradle
  src/main/java/com/samyookgoo/palgoosam/bid/domain/Bid.java
  src/main/java/com/samyookgoo/palgoosam/deliveryaddress/domain/DeliveryAddress.java
  src/main/java/com/samyookgoo/palgoosam/payment/service/PaymentService.java
  src/main/java/com/samyookgoo/palgoosam/search/domain/SearchHistory.java
  src/test/resources/application-test.yml
Labels: Chore, Backend

#176 Chore: Gradle에 Jacoco 관련 설정 수정 및 추가
  build.gradle
Labels: Chore, Backend

#177 Test: Bid 관련 Presentation / Business Layer 테스트 코드 추가
  src/main/java/com/samyookgoo/palgoosam/bid/controller/BidController.java
  src/main/java/com/samyookgoo/palgoosam/bid/controller/request/BidRequest.java
  src/main/java/com/samyookgoo/palgoosam/bid/domain/Bid.java
  src/main/java/com/samyookgoo/palgoosam/bid/repository/BidRepository.java
  src/main/java/com/samyookgoo/palgoosam/bid/service/BidService.java
  src/test/java/com/samyookgoo/palgoosam/bid/controller/BidControllerTest.java
  src/test/java/com/samyookgoo/palgoosam/bid/controller/SseControllerTest.java
  src/test/java/com/samyookgoo/palgoosam/bid/repository/BidRepositoryTest.java
  src/test/java/com/samyookgoo/palgoosam/bid/service/BidServiceTest.java
  src/test/java/com/samyookgoo/palgoosam/bid/service/SseServiceTest.java
Labels: Test, Backend

#180 Test: PaymentService 테스트 추가 및 리팩토링
  src/main/java/com/samyookgoo/palgoosam/bid/domain/Bid.java
  src/main/java/com/samyookgoo/palgoosam/global/exception/ErrorCode.java
  src/main/java/com/samyookgoo/palgoosam/payment/controller/PaymentController.java
  src/main/java/com/samyookgoo/palgoosam/payment/controller/request/PaymentCreateRequest.java
  src/main/java/com/samyookgoo/palgoosam/payment/controller/request/TossPaymentConfirmRequest.java
  src/main/java/com/samyookgoo/palgoosam/payment/controller/request/TossPaymentFailCallbackRequest.java
  src/main/java/com/samyookgoo/palgoosam/payment/controller/response/PaymentCreateResponse.java
  src/main/java/com/samyookgoo/palgoosam/payment/controller/response/TossPaymentConfirmResponse.java
  src/main/java/com/samyookgoo/palgoosam/payment/domain/Payment.java
  src/main/java/com/samyookgoo/palgoosam/payment/policy/DeliveryPolicy.java
  src/main/java/com/samyookgoo/palgoosam/payment/repository/PaymentRepository.java
  src/main/java/com/samyookgoo/palgoosam/payment/service/PaymentService.java
  src/test/java/com/samyookgoo/palgoosam/payment/service/PaymentServiceTest.java
Labels: Refactor, Test, Backend

#183 Feat: 입찰 내역 조회 시 입찰자 닉네임 마스킹 처리 추가
  src/main/java/com/samyookgoo/palgoosam/bid/controller/response/BidResponse.java
Labels: Feature, Backend

#185 Test: PaymentController, PaymentRepository 테스트 코드 구현
  src/test/java/com/samyookgoo/palgoosam/payment/controller/PaymentControllerTest.java
  src/test/java/com/samyookgoo/palgoosam/payment/repository/PaymentRepositoryTest.java
Labels: Test, Backend

#187 Fix: BidServiceTest 입찰 내역의 입찰자 확인 부분 수정
  src/test/java/com/samyookgoo/palgoosam/bid/service/BidServiceTest.java
Labels: Hot Fix, Backend

#181 Test: User 도메인 리팩토링 및 테스트 코드 작성
  src/main/java/com/samyookgoo/palgoosam/auction/repository/AuctionRepository.java
  src/main/java/com/samyookgoo/palgoosam/bid/repository/BidRepository.java
  src/main/java/com/samyookgoo/palgoosam/user/service/UserService.java
  src/test/java/com/samyookgoo/palgoosam/auction/unit_test/AuctionRepositoryTest.java
  src/test/java/com/samyookgoo/palgoosam/bid/unit_test/BidRepositoryTest.java
  src/test/java/com/samyookgoo/palgoosam/payment/unit_test/PaymentRepositoryTest.java
  src/test/java/com/samyookgoo/palgoosam/user/integration_test/UserServiceBusinessLogicTest.java
  src/test/java/com/samyookgoo/palgoosam/user/unit_test/UserResponseDtoTest.java
Labels: Refactor, Test, Backend

#189 Test: test코드의 DB 사용 설정 수정
  src/test/java/com/samyookgoo/palgoosam/bid/repository/BidRepositoryTest.java
  src/test/java/com/samyookgoo/palgoosam/bid/service/BidServiceTest.java
  src/test/java/com/samyookgoo/palgoosam/payment/repository/PaymentRepositoryTest.java
  src/test/java/com/samyookgoo/palgoosam/payment/service/PaymentServiceTest.java
  src/test/java/com/samyookgoo/palgoosam/search/integration_test/SearchHistoryServiceBusinessLogicTest.java
Labels: Test, Backend

#192 Chore: EC2 API 서버용 Dockerfile 작성
  Dockerfile
Labels: Chore, Backend

#193 Chore: env 파일 설정
  .gitignore
  src/main/java/com/samyookgoo/palgoosam/bid/controller/BidController.java
  src/main/java/com/samyookgoo/palgoosam/config/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/samyookgoo/palgoosam/config/PropertyConfig.java
  src/main/java/com/samyookgoo/palgoosam/config/SecurityConfig.java
  src/main/java/com/samyookgoo/palgoosam/config/WebMvcConfig.java
  src/main/java/com/samyookgoo/palgoosam/deliveryaddress/controller/DeliveryAddressController.java
  src/main/java/com/samyookgoo/palgoosam/user/controller/UserController.java
Labels: Chore, Backend

#194 chore: cd 스크립트 작성
  .github/workflows/deploy_palgoosam_api_server.yml
Labels: Chore

#201 fix: netcat 명시적으로 설치할 수 있도록 수정
  .github/workflows/deploy_palgoosam_api_server.yml
Labels: Chore

#208 Fix: application-test.yml 에 서버 포트 추가
  src/test/resources/application-test.yml
Labels: Bug Fix, Backend

#215 Feat: 이미지 S3 Presigned Url 연동
  src/main/java/com/samyookgoo/palgoosam/auction/controller/AuctionController.java
  src/main/java/com/samyookgoo/palgoosam/auction/domain/AuctionImage.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/request/AuctionCreateRequest.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/request/AuctionImageRequest.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/request/AuctionUpdateRequest.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/response/AuctionCreateResponse.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/response/AuctionImageResponse.java
  src/main/java/com/samyookgoo/palgoosam/auction/file/FileStore.java
  src/main/java/com/samyookgoo/palgoosam/auction/file/ResultFileStore.java
  src/main/java/com/samyookgoo/palgoosam/auction/repository/AuctionImageRepository.java
  src/main/java/com/samyookgoo/palgoosam/auction/service/AuctionService.java
  src/main/java/com/samyookgoo/palgoosam/common/s3/S3Controller.java
  src/main/java/com/samyookgoo/palgoosam/common/s3/S3PresignedRequest.java
  src/main/java/com/samyookgoo/palgoosam/common/s3/S3PresignedResponse.java
  src/main/java/com/samyookgoo/palgoosam/common/s3/S3Service.java
  src/main/java/com/samyookgoo/palgoosam/common/service/S3Service.java
  src/main/java/com/samyookgoo/palgoosam/config/AwsS3Config.java
Labels: Feature, Backend

#257 Chore: prometheus 적용을 위한 설정 코드 추가
  build.gradle
  src/main/java/com/samyookgoo/palgoosam/config/SecurityConfig.java
Labels: Chore, Backend

#261 입찰 기능 동시성 제어 로직 구현 (Redis Lock + Pub/Sub 방식)
  build.gradle
  src/main/java/com/samyookgoo/palgoosam/bid/api_docs/SseAuctionSubscribeApi.java
  src/main/java/com/samyookgoo/palgoosam/bid/api_docs/SseUserSubscribeApi.java
  src/main/java/com/samyookgoo/palgoosam/bid/controller/BidController.java
  src/main/java/com/samyookgoo/palgoosam/bid/controller/SseController.java
  src/main/java/com/samyookgoo/palgoosam/bid/domain/Bid.java
  src/main/java/com/samyookgoo/palgoosam/bid/repository/BidRepository.java
  src/main/java/com/samyookgoo/palgoosam/bid/service/BidExecutorService.java
  src/main/java/com/samyookgoo/palgoosam/bid/service/BidService.java
  src/main/java/com/samyookgoo/palgoosam/bid/service/SseService.java
  src/main/java/com/samyookgoo/palgoosam/bid/service/listener/BidEventListener.java
  src/main/java/com/samyookgoo/palgoosam/bid/service/listener/LockEventListener.java
  src/main/java/com/samyookgoo/palgoosam/bid/service/response/BidFailedEvent.java
  src/main/java/com/samyookgoo/palgoosam/bid/service/response/BidSuccessEvent.java
  src/main/java/com/samyookgoo/palgoosam/bid/service/response/LockReleaseEvent.java
  src/main/java/com/samyookgoo/palgoosam/common/event/LockReleaseEventListener.java
  src/main/java/com/samyookgoo/palgoosam/common/lock/LockInfo.java
  src/main/java/com/samyookgoo/palgoosam/common/lock/LockRetryHandler.java
  src/main/java/com/samyookgoo/palgoosam/common/lock/TaskWrapper.java
  src/main/java/com/samyookgoo/palgoosam/common/service/RedisLockService.java
  src/main/java/com/samyookgoo/palgoosam/config/RedisConfig.java
  src/main/java/com/samyookgoo/palgoosam/global/exception/ErrorCode.java
  src/test/java/com/samyookgoo/palgoosam/bid/controller/BidControllerTest.java
  src/test/java/com/samyookgoo/palgoosam/bid/controller/SseControllerTest.java
  src/test/java/com/samyookgoo/palgoosam/bid/service/BidServiceTest.java
  src/test/java/com/samyookgoo/palgoosam/bid/service/SseServiceTest.java
Labels: Perf, Refactor, Backend

#263 Feat: 경매 상태 전환 스케줄링 고도화
  src/main/java/com/samyookgoo/palgoosam/auction/repository/AuctionRepository.java
  src/main/java/com/samyookgoo/palgoosam/auction/scheduler/AuctionStatusScheduler.java
  src/main/java/com/samyookgoo/palgoosam/auction/service/AuctionService.java
  src/main/java/com/samyookgoo/palgoosam/auction/service/AuctionStatusService.java
  src/main/java/com/samyookgoo/palgoosam/bid/service/SseService.java
  src/main/java/com/samyookgoo/palgoosam/schedule/AuctionStatusEventResponse.java
  src/main/java/com/samyookgoo/palgoosam/schedule/AuctionStatusPayload.java
  src/main/java/com/samyookgoo/palgoosam/schedule/AuctionStatusPublisher.java
  src/main/java/com/samyookgoo/palgoosam/schedule/AuctionStatusSubscriber.java
  src/main/java/com/samyookgoo/palgoosam/schedule/JacksonConfig.java
  src/main/java/com/samyookgoo/palgoosam/schedule/RedisConfig.java
  src/main/java/com/samyookgoo/palgoosam/schedule/RedisKeyExpirationListener.java
  src/main/java/com/samyookgoo/palgoosam/schedule/RedisListenerConfig.java
Labels: Feature, Backend
