Repository goorm-369/893-back, pull requests merged in 2025-05, with the labels that each got.

#20 Feature/entity
  build.gradle
  src/main/java/com/samyookgoo/palgoosam/auction/.gitkeep
  src/main/java/com/samyookgoo/palgoosam/auction/domain/Auction.java
  src/main/java/com/samyookgoo/palgoosam/auction/domain/AuctionImage.java
  src/main/java/com/samyookgoo/palgoosam/auction/domain/Category.java
  src/main/java/com/samyookgoo/palgoosam/bid/.gitkeep
  src/main/java/com/samyookgoo/palgoosam/bid/domain/Bid.java
  src/main/java/com/samyookgoo/palgoosam/notification/.gitkeep
  src/main/java/com/samyookgoo/palgoosam/notification/domain/NotificationHistory.java
  src/main/java/com/samyookgoo/palgoosam/notification/domain/NotificationType.java
  src/main/java/com/samyookgoo/palgoosam/payment/.gitkeep
  src/main/java/com/samyookgoo/palgoosam/payment/domain/Payment.java
  src/main/java/com/samyookgoo/palgoosam/search/.gitkeep
  src/main/java/com/samyookgoo/palgoosam/search/domain/SearchHistory.java
  src/main/java/com/samyookgoo/palgoosam/user/.gitkeep
  src/main/java/com/samyookgoo/palgoosam/user/domain/DeliveryAddress.java
  src/main/java/com/samyookgoo/palgoosam/user/domain/Scrap.java
  src/main/java/com/samyookgoo/palgoosam/user/domain/User.java
  src/main/java/com/samyookgoo/palgoosam/user/domain/UserNotificationToken.java
  src/main/java/com/samyookgoo/palgoosam/user/domain/UserOauthToken.java
  src/main/resources/application.yml
Labels: Feature

#26 Feat: 경매 상품 등록 기능 구현
  src/main/java/com/samyookgoo/palgoosam/auction/controller/AuctionController.java
  src/main/java/com/samyookgoo/palgoosam/auction/domain/Auction.java
  src/main/java/com/samyookgoo/palgoosam/auction/domain/AuctionImage.java
  src/main/java/com/samyookgoo/palgoosam/auction/domain/Category.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/AuctionCreateRequest.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/itemCondition.java
  src/main/java/com/samyookgoo/palgoosam/auction/file/FileStore.java
  src/main/java/com/samyookgoo/palgoosam/auction/file/ResultFileStore.java
  src/main/java/com/samyookgoo/palgoosam/auction/repository/AuctionImageRepository.java
  src/main/java/com/samyookgoo/palgoosam/auction/repository/AuctionRepository.java
  src/main/java/com/samyookgoo/palgoosam/auction/repository/CategoryRepository.java
  src/main/java/com/samyookgoo/palgoosam/auction/service/AuctionService.java
  src/main/java/com/samyookgoo/palgoosam/user/domain/User.java
  src/main/java/com/samyookgoo/palgoosam/user/repository/UserRepository.java
  src/main/resources/application.yml
Labels: Feature, Backend

#27 Feat: 검색 페이지 조회 API 구현
  sql/init_mock_data.sql
  sql/init_schema.sql
  src/main/java/com/samyookgoo/palgoosam/auction/constant/AuctionStatus.java
  src/main/java/com/samyookgoo/palgoosam/auction/constant/ItemCondition.java
  src/main/java/com/samyookgoo/palgoosam/auction/controller/AuctionController.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/AuctionSearchParam.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/AuctionSearchRequestDto.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/AuctionSearchResponseDto.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/AuctionSearchResultDto.java
  src/main/java/com/samyookgoo/palgoosam/auction/repository/AuctionImageRepository.java
  src/main/java/com/samyookgoo/palgoosam/auction/repository/AuctionRepository.java
  src/main/java/com/samyookgoo/palgoosam/auction/service/AuctionService.java
  src/main/java/com/samyookgoo/palgoosam/bid/domain/Bid.java
  src/main/java/com/samyookgoo/palgoosam/bid/repository/BidRepository.java
  src/main/java/com/samyookgoo/palgoosam/user/domain/Scrap.java
  src/main/java/com/samyookgoo/palgoosam/user/repository/ScrapRepository.java
Labels: Feature, Backend

#28 Feat: 경매 상품 상세 조회 API 구현
  src/main/java/com/samyookgoo/palgoosam/auction/controller/AuctionController.java
  src/main/java/com/samyookgoo/palgoosam/auction/domain/AuctionImage.java
  src/main/java/com/samyookgoo/palgoosam/auction/domain/Category.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/AuctionCreateRequest.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/AuctionDetailResponse.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/AuctionImageResponse.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/ImageDto.java
  src/main/java/com/samyookgoo/palgoosam/auction/repository/AuctionImageRepository.java
  src/main/java/com/samyookgoo/palgoosam/auction/repository/AuctionRepository.java
  src/main/java/com/samyookgoo/palgoosam/auction/service/AuctionService.java
  src/main/java/com/samyookgoo/palgoosam/user/domain/User.java
Labels: Feature, Backend

#33 hotfix: auction controller와 auction iamge 수정, API 명세대로 반환하도록 검색 API 수정
  src/main/java/com/samyookgoo/palgoosam/auction/controller/AuctionController.java
  src/main/java/com/samyookgoo/palgoosam/auction/domain/AuctionImage.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/AuctionListItemDto.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/AuctionSearchResponseDto.java
  src/main/java/com/samyookgoo/palgoosam/auction/service/AuctionService.java
  src/main/java/com/samyookgoo/palgoosam/common/.gitkeep
  src/main/java/com/samyookgoo/palgoosam/common/response/BaseResponse.java
  src/main/java/com/samyookgoo/palgoosam/user/domain/UserFcmToken.java
Labels: Hot Fix, Backend

#31 Feat: 경매 입찰 조회/등록/취소 API 구현
  .gitignore
  sql/init_schema.sql
  src/main/java/com/samyookgoo/palgoosam/bid/controller/BidController.java
  src/main/java/com/samyookgoo/palgoosam/bid/controller/request/BidRequest.java
  src/main/java/com/samyookgoo/palgoosam/bid/controller/response/BaseResponse.java
  src/main/java/com/samyookgoo/palgoosam/bid/controller/response/BidListResponse.java
  src/main/java/com/samyookgoo/palgoosam/bid/controller/response/BidResponse.java
  src/main/java/com/samyookgoo/palgoosam/bid/domain/Bid.java
  src/main/java/com/samyookgoo/palgoosam/bid/repository/BidRepository.java
  src/main/java/com/samyookgoo/palgoosam/bid/service/BidService.java
  src/main/java/com/samyookgoo/palgoosam/common/validation/DivisibleBy.java
  src/main/java/com/samyookgoo/palgoosam/common/validation/DivisibleByValidator.java
  src/main/resources/application.yml
Labels: Feature, Backend

#36 Hotfix: User 및 AuctionImage 엔티티의 어노테이션 정리 및 중복 제거
  src/main/java/com/samyookgoo/palgoosam/auction/domain/AuctionImage.java
  src/main/java/com/samyookgoo/palgoosam/user/domain/User.java
Labels: Hot Fix, Backend

#37 Feat: fcm 토큰 저장 API 구현
  .gitignore
  build.gradle
  sql/init_mock_data.sql
  sql/init_schema.sql
  src/main/java/com/samyookgoo/palgoosam/notification/controller/NotificationController.java
  src/main/java/com/samyookgoo/palgoosam/notification/domain/UserFcmToken.java
  src/main/java/com/samyookgoo/palgoosam/notification/dto/FcmTokenSaveRequestDto.java
  src/main/java/com/samyookgoo/palgoosam/notification/repository/UserFcmTokenRepository.java
  src/main/java/com/samyookgoo/palgoosam/notification/service/FcmInitialization.java
  src/main/java/com/samyookgoo/palgoosam/notification/service/FirebaseCloudMessageService.java
  src/main/java/com/samyookgoo/palgoosam/notification/service/NotificationService.java
Labels: Feature, Backend

#38 Feat : 인증 관련 기능 및 API 구현
  build.gradle
  src/main/java/com/samyookgoo/palgoosam/auth/CustomOauth2UserDetails.java
  src/main/java/com/samyookgoo/palgoosam/auth/CustomOidcUserService.java
  src/main/java/com/samyookgoo/palgoosam/auth/JwtAuthenticationFilter.java
  src/main/java/com/samyookgoo/palgoosam/auth/JwtTokenProvider.java
  src/main/java/com/samyookgoo/palgoosam/auth/controller/AuthController.java
  src/main/java/com/samyookgoo/palgoosam/auth/service/AuthService.java
  src/main/java/com/samyookgoo/palgoosam/config/OAuth2AuthenticationFailureHandler.java
  src/main/java/com/samyookgoo/palgoosam/config/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/samyookgoo/palgoosam/config/SecurityConfig.java
  src/main/java/com/samyookgoo/palgoosam/user/controller/UserController.java
  src/main/java/com/samyookgoo/palgoosam/user/domain/User.java
  src/main/java/com/samyookgoo/palgoosam/user/domain/UserJwtToken.java
  src/main/java/com/samyookgoo/palgoosam/user/dto/UserInfoResponseDto.java
  src/main/java/com/samyookgoo/palgoosam/user/repository/UserJwtTokenRepository.java
  src/main/java/com/samyookgoo/palgoosam/user/repository/UserRepository.java
  src/main/resources/application.yml
Labels: Feature, Backend

#40 Hotfix: import 추가 및 파일명 수정
  src/main/java/com/samyookgoo/palgoosam/auction/controller/AuctionController.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/ItemCondition.java
  src/main/java/com/samyookgoo/palgoosam/auction/repository/AuctionImageRepository.java
Labels: Bug Fix, Backend

#35 Feat: 검색 기록 조회 API 구현
  src/main/java/com/samyookgoo/palgoosam/search/controller/SearchHistoryController.java
  src/main/java/com/samyookgoo/palgoosam/search/dto/SearchHistoryResponseDto.java
  src/main/java/com/samyookgoo/palgoosam/search/repository/SearchHistoryRepository.java
  src/main/java/com/samyookgoo/palgoosam/search/service/SearchHistoryService.java
Labels: Feature, Backend

#43 Feat: 경매 삭제 API 구현 및 전체 API 수정
  src/main/java/com/samyookgoo/palgoosam/auction/controller/AuctionController.java
  src/main/java/com/samyookgoo/palgoosam/auction/domain/Auction.java
  src/main/java/com/samyookgoo/palgoosam/auction/domain/AuctionImage.java
  src/main/java/com/samyookgoo/palgoosam/auction/domain/AuctionStatus.java
  src/main/java/com/samyookgoo/palgoosam/auction/domain/Category.java
  src/main/java/com/samyookgoo/palgoosam/auction/domain/ItemCondition.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/AuctionCreateRequest.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/AuctionDetailResponse.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/AuctionImageResponse.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/AuctionUpdateRequest.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/ImageDto.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/request/AuctionCreateRequest.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/request/AuctionImageRequest.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/request/AuctionUpdateRequest.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/request/CategoryRequest.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/response/AuctionCreateResponse.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/response/AuctionDetailResponse.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/response/AuctionImageResponse.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/response/AuctionUpdatePageResponse.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/response/AuctionUpdateResponse.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/response/CategoryResponse.java
  src/main/java/com/samyookgoo/palgoosam/auction/file/FileStore.java
  src/main/java/com/samyookgoo/palgoosam/auction/file/ResultFileStore.java
  src/main/java/com/samyookgoo/palgoosam/auction/repository/AuctionImageRepository.java
  src/main/java/com/samyookgoo/palgoosam/auction/repository/AuctionRepository.java
  src/main/java/com/samyookgoo/palgoosam/auction/repository/CategoryRepository.java
  src/main/java/com/samyookgoo/palgoosam/auction/service/AuctionService.java
Labels: Feature, Backend

#44 Feat: 검색어 자동완성 API 구현
  sql/init_mock_data.sql
  src/main/java/com/samyookgoo/palgoosam/auction/dto/ItemCondition.java
  src/main/java/com/samyookgoo/palgoosam/search/controller/SearchHistoryController.java
  src/main/java/com/samyookgoo/palgoosam/search/repository/SearchHistoryRepository.java
  src/main/java/com/samyookgoo/palgoosam/search/service/SearchHistoryService.java
Labels: Feature, Backend

#51 Fix: Pagination 버그 수정
  src/main/java/com/samyookgoo/palgoosam/auction/dto/AuctionListItemDto.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/AuctionSearchParam.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/AuctionSearchRequestDto.java
  src/main/java/com/samyookgoo/palgoosam/auction/repository/AuctionRepository.java
  src/main/java/com/samyookgoo/palgoosam/auction/service/AuctionService.java
Labels: Bug Fix, Backend

#48 Feat: Scrap API 구현
  src/main/java/com/samyookgoo/palgoosam/auction/controller/ScrapController.java
  src/main/java/com/samyookgoo/palgoosam/auction/service/ScrapService.java
  src/main/java/com/samyookgoo/palgoosam/user/domain/Scrap.java
  src/main/java/com/samyookgoo/palgoosam/user/repository/ScrapRepository.java
Labels: Feature, Backend

#50 Feat: 경매 실시간 입찰 정보 전송을 위한 SSE 기능 구현
  src/main/java/com/samyookgoo/palgoosam/bid/controller/BidController.java
  src/main/java/com/samyookgoo/palgoosam/bid/controller/SseController.java
  src/main/java/com/samyookgoo/palgoosam/bid/controller/response/BidEventResponse.java
  src/main/java/com/samyookgoo/palgoosam/bid/repository/BidRepository.java
  src/main/java/com/samyookgoo/palgoosam/bid/service/BidService.java
  src/main/java/com/samyookgoo/palgoosam/bid/service/SseService.java
Labels: Feature, Refactor, Backend

#54 Hotfix: Auction 관련 누락된 코드 추가 및 중복 어노테이션 정리
  src/main/java/com/samyookgoo/palgoosam/auction/controller/AuctionController.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/AuctionListItemDto.java
  src/main/java/com/samyookgoo/palgoosam/auction/repository/AuctionImageRepository.java
  src/main/java/com/samyookgoo/palgoosam/user/domain/Scrap.java
  src/main/java/com/samyookgoo/palgoosam/user/repository/ScrapRepository.java
Labels: Hot Fix, Backend

#52 feat : 마이페이지 API 구현 및 서비스 레이어 분리
  src/main/java/com/samyookgoo/palgoosam/auction/repository/AuctionImageRepository.java
  src/main/java/com/samyookgoo/palgoosam/auction/repository/AuctionRepository.java
  src/main/java/com/samyookgoo/palgoosam/auction/service/AuctionImageService.java
  src/main/java/com/samyookgoo/palgoosam/auction/service/AuctionService.java
  src/main/java/com/samyookgoo/palgoosam/bid/projection/AuctionMaxBid.java
  src/main/java/com/samyookgoo/palgoosam/bid/projection/MainImageProjection.java
  src/main/java/com/samyookgoo/palgoosam/bid/repository/BidRepository.java
  src/main/java/com/samyookgoo/palgoosam/bid/service/BidService.java
  src/main/java/com/samyookgoo/palgoosam/deliveryaddress/controller/DeliveryAddressController.java
  src/main/java/com/samyookgoo/palgoosam/deliveryaddress/domain/DeliveryAddress.java
  src/main/java/com/samyookgoo/palgoosam/deliveryaddress/dto/DeliveryAddressRequestDto.java
  src/main/java/com/samyookgoo/palgoosam/deliveryaddress/dto/DeliveryAddressResponseDto.java
  src/main/java/com/samyookgoo/palgoosam/deliveryaddress/repository/DeliveryAddressRepository.java
  src/main/java/com/samyookgoo/palgoosam/deliveryaddress/service/DeliveryAddressService.java
  src/main/java/com/samyookgoo/palgoosam/payment/domain/Payment.java
  src/main/java/com/samyookgoo/palgoosam/payment/repository/PaymentRepository.java
  src/main/java/com/samyookgoo/palgoosam/user/controller/UserController.java
  src/main/java/com/samyookgoo/palgoosam/user/dto/UserAuctionsResponseDto.java
  src/main/java/com/samyookgoo/palgoosam/user/dto/UserBidsResponseDto.java
  src/main/java/com/samyookgoo/palgoosam/user/dto/UserPaymentsResponseDto.java
  src/main/java/com/samyookgoo/palgoosam/user/repository/ScrapRepository.java
  src/main/java/com/samyookgoo/palgoosam/user/service/UserService.java
Labels: Feature, Refactor, Backend

#57 Feat: BidController에 인증된 사용자 연동
  src/main/java/com/samyookgoo/palgoosam/bid/controller/BidController.java
Labels: Feature, Backend

#56 Feat 연관 상품 목록 조회 api 구현
  src/main/java/com/samyookgoo/palgoosam/auction/controller/AuctionController.java
  src/main/java/com/samyookgoo/palgoosam/auction/controller/ScrapController.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/request/AuctionUpdateRequest.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/response/AuctionDetailResponse.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/response/AuctionUpdatePageResponse.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/response/CategoryResponse.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/response/RelatedAuctionResponse.java
  src/main/java/com/samyookgoo/palgoosam/auction/file/FileStore.java
  src/main/java/com/samyookgoo/palgoosam/auction/repository/AuctionImageRepository.java
  src/main/java/com/samyookgoo/palgoosam/auction/repository/AuctionRepository.java
  src/main/java/com/samyookgoo/palgoosam/auction/service/AuctionService.java
  src/main/java/com/samyookgoo/palgoosam/config/.gitkeep
Labels: Feature, Backend

#59 Hotfix/rename repository methods
  src/main/java/com/samyookgoo/palgoosam/auction/repository/AuctionImageRepository.java
  src/main/java/com/samyookgoo/palgoosam/auction/service/AuctionImageService.java
  src/main/java/com/samyookgoo/palgoosam/user/dto/UserAuctionsResponseDto.java
  src/main/java/com/samyookgoo/palgoosam/user/dto/UserBidsResponseDto.java
Labels: Hot Fix, Backend

#60 Feat: 알림 내역 조회 API 구현
  src/main/java/com/samyookgoo/palgoosam/notification/controller/NotificationController.java
  src/main/java/com/samyookgoo/palgoosam/notification/dto/NotificationResponseDto.java
  src/main/java/com/samyookgoo/palgoosam/notification/repository/NotificationStatusRepository.java
  src/main/java/com/samyookgoo/palgoosam/notification/service/NotificationService.java
  src/main/java/com/samyookgoo/palgoosam/notification/subscription/repository/AuctionSubscriptionRepository.java
Labels: Feature, Backend

#61 Feat: 알림 상태 업데이트 API 구현
  src/main/java/com/samyookgoo/palgoosam/notification/controller/NotificationController.java
  src/main/java/com/samyookgoo/palgoosam/notification/repository/NotificationStatusRepository.java
  src/main/java/com/samyookgoo/palgoosam/notification/service/NotificationService.java
Labels: Feature, Backend

#63 Feat: WebMvcConfig 파일 추가
  src/main/java/com/samyookgoo/palgoosam/config/SecurityConfig.java
  src/main/java/com/samyookgoo/palgoosam/config/WebMvcConfig.java
Labels: Feature, Backend

#65 Feat: 경매 상품 결제 API 구현
  src/main/java/com/samyookgoo/palgoosam/config/TossPaymentsConfig.java
  src/main/java/com/samyookgoo/palgoosam/payment/controller/PaymentController.java
  src/main/java/com/samyookgoo/palgoosam/payment/controller/request/CreatePaymentRequest.java
  src/main/java/com/samyookgoo/palgoosam/payment/controller/response/PaymentResponse.java
  src/main/java/com/samyookgoo/palgoosam/payment/domain/Payment.java
  src/main/java/com/samyookgoo/palgoosam/payment/domain/PaymentMethod.java
  src/main/java/com/samyookgoo/palgoosam/payment/domain/PaymentStatus.java
  src/main/java/com/samyookgoo/palgoosam/payment/repository/PaymentRepository.java
  src/main/java/com/samyookgoo/palgoosam/payment/service/PaymentService.java
  src/main/resources/application.yml
Labels: Feature, Backend

#66 Hotfix: Payment 엔티티 어노테이션 추가
  src/main/java/com/samyookgoo/palgoosam/payment/domain/Payment.java
Labels: Hot Fix, Backend

#67 Feat 이미지 업로드 오류 수정
  src/main/java/com/samyookgoo/palgoosam/auction/dto/response/AuctionImageResponse.java
  src/main/java/com/samyookgoo/palgoosam/auction/service/AuctionService.java
Labels: Feature, Backend

#69 Feat 경매 상품 주문페이지 조회 API 구
  src/main/java/com/samyookgoo/palgoosam/auction/repository/AuctionImageRepository.java
  src/main/java/com/samyookgoo/palgoosam/auction/service/AuctionService.java
  src/main/java/com/samyookgoo/palgoosam/deliveryaddress/dto/DeliveryAddressResponseDto.java
  src/main/java/com/samyookgoo/palgoosam/deliveryaddress/repository/DeliveryAddressRepository.java
  src/main/java/com/samyookgoo/palgoosam/payment/controller/OrderController.java
  src/main/java/com/samyookgoo/palgoosam/payment/controller/response/OrderResponse.java
  src/main/java/com/samyookgoo/palgoosam/payment/service/PaymentService.java
Labels: Feature, Backend

#74 Feat 경매 상품 상태 전환 기능 구현
  src/main/java/com/samyookgoo/palgoosam/PalgoosamApplication.java
  src/main/java/com/samyookgoo/palgoosam/auction/repository/AuctionRepository.java
  src/main/java/com/samyookgoo/palgoosam/auction/scheduler/AuctionStatusScheduler.java
Labels: Feature, Backend

#76 Feat 로그인 유저 조회 로직 적용
  src/main/java/com/samyookgoo/palgoosam/auction/service/AuctionService.java
  src/main/java/com/samyookgoo/palgoosam/auction/service/ScrapService.java
Labels: Feature, Backend

#77 Refactor: authService를 통해 로그인 사용자를 가져오도록 코드 수정
  src/main/java/com/samyookgoo/palgoosam/auction/service/AuctionService.java
  src/main/java/com/samyookgoo/palgoosam/auth/service/AuthService.java
  src/main/java/com/samyookgoo/palgoosam/notification/controller/NotificationController.java
  src/main/java/com/samyookgoo/palgoosam/notification/fcm/service/FirebaseCloudMessageService.java
  src/main/java/com/samyookgoo/palgoosam/notification/service/NotificationService.java
  src/main/java/com/samyookgoo/palgoosam/notification/subscription/service/AuctionSubscriptionService.java
  src/main/java/com/samyookgoo/palgoosam/search/service/SearchHistoryService.java
Labels: Feature, Backend

#73 Feat: 경매 상품 결제 승인 API 구현
  sql/init_mock_data.sql
  src/main/java/com/samyookgoo/palgoosam/payment/controller/PaymentController.java
  src/main/java/com/samyookgoo/palgoosam/payment/controller/request/PaymentConfirmRequest.java
  src/main/java/com/samyookgoo/palgoosam/payment/controller/response/PaymentConfirmResponse.java
  src/main/java/com/samyookgoo/palgoosam/payment/domain/Payment.java
  src/main/java/com/samyookgoo/palgoosam/payment/repository/PaymentRepository.java
  src/main/java/com/samyookgoo/palgoosam/payment/service/PaymentService.java
Labels: Feature, Backend

#75 Feat: 경매 상품 결제 실패 처리 API 구현
  src/main/java/com/samyookgoo/palgoosam/payment/controller/PaymentController.java
  src/main/java/com/samyookgoo/palgoosam/payment/controller/request/PaymentFailRequest.java
  src/main/java/com/samyookgoo/palgoosam/payment/service/PaymentService.java
Labels: Feature, Backend

#79 Fix: 유저 널 체크 로직 추가
  src/main/java/com/samyookgoo/palgoosam/auction/dto/response/RelatedAuctionResponse.java
  src/main/java/com/samyookgoo/palgoosam/auction/service/AuctionService.java
  src/main/java/com/samyookgoo/palgoosam/auction/service/ScrapService.java
  src/main/java/com/samyookgoo/palgoosam/auth/controller/AuthController.java
  src/main/java/com/samyookgoo/palgoosam/bid/controller/BidController.java
  src/main/java/com/samyookgoo/palgoosam/deliveryaddress/controller/DeliveryAddressController.java
  src/main/java/com/samyookgoo/palgoosam/payment/controller/OrderController.java
  src/main/java/com/samyookgoo/palgoosam/payment/controller/PaymentController.java
  src/main/java/com/samyookgoo/palgoosam/user/controller/UserController.java
Labels: Feature, Backend

#53 Hotfix: 인증 화이트리스트 추가
  src/main/java/com/samyookgoo/palgoosam/auth/JwtAuthenticationFilter.java
  src/main/java/com/samyookgoo/palgoosam/config/OAuth2AuthenticationFailureHandler.java
  src/main/java/com/samyookgoo/palgoosam/config/SecurityConfig.java
Labels: Hot Fix, Backend

#81 fix: fix payment feature
  src/main/java/com/samyookgoo/palgoosam/payment/controller/request/CreatePaymentRequest.java
  src/main/java/com/samyookgoo/palgoosam/payment/domain/PaymentMethod.java
  src/main/java/com/samyookgoo/palgoosam/payment/service/PaymentService.java
Labels: Feature, Backend

#82 fix: fix security config
  src/main/java/com/samyookgoo/palgoosam/auth/JwtAuthenticationFilter.java
  src/main/java/com/samyookgoo/palgoosam/config/OAuth2AuthenticationFailureHandler.java
  src/main/java/com/samyookgoo/palgoosam/config/SecurityConfig.java
Labels: Hot Fix, Backend

#86 Hotfix: 경매 결제 승인 API 파싱 에러 수정
  src/main/java/com/samyookgoo/palgoosam/payment/service/PaymentService.java
Labels: Hot Fix, Backend

#88 Feat: Swagger 설정
  build.gradle
  src/main/java/com/samyookgoo/palgoosam/auction/controller/AuctionController.java
  src/main/java/com/samyookgoo/palgoosam/auction/controller/ScrapController.java
  src/main/java/com/samyookgoo/palgoosam/auction/domain/Auction.java
  src/main/java/com/samyookgoo/palgoosam/auction/domain/AuctionImage.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/response/AuctionCreateResponse.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/response/AuctionDetailResponse.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/response/AuctionImageResponse.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/response/AuctionUpdatePageResponse.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/response/AuctionUpdateResponse.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/response/CategoryResponse.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/response/RelatedAuctionResponse.java
  src/main/java/com/samyookgoo/palgoosam/auth/JwtAuthenticationFilter.java
  src/main/java/com/samyookgoo/palgoosam/auth/controller/AuthController.java
  src/main/java/com/samyookgoo/palgoosam/bid/controller/BidController.java
  src/main/java/com/samyookgoo/palgoosam/bid/controller/SseController.java
  src/main/java/com/samyookgoo/palgoosam/common/response/BaseResponse.java
  src/main/java/com/samyookgoo/palgoosam/config/SecurityConfig.java
  src/main/java/com/samyookgoo/palgoosam/config/SwaggerConfig.java
  src/main/java/com/samyookgoo/palgoosam/deliveryaddress/controller/DeliveryAddressController.java
  src/main/java/com/samyookgoo/palgoosam/deliveryaddress/domain/DeliveryAddress.java
  src/main/java/com/samyookgoo/palgoosam/notification/controller/NotificationController.java
  src/main/java/com/samyookgoo/palgoosam/payment/controller/OrderController.java
  src/main/java/com/samyookgoo/palgoosam/payment/controller/PaymentController.java
  src/main/java/com/samyookgoo/palgoosam/payment/controller/response/OrderResponse.java
  src/main/java/com/samyookgoo/palgoosam/payment/domain/Payment.java
  src/main/java/com/samyookgoo/palgoosam/search/controller/SearchHistoryController.java
  src/main/java/com/samyookgoo/palgoosam/user/controller/UserController.java
  src/main/java/com/samyookgoo/palgoosam/user/domain/Scrap.java
  src/main/resources/application.yml
Labels: Feature, Backend

#87 fix: 경매 리스트 반환 시 limit의 디폴트를 12로 수정
  src/main/java/com/samyookgoo/palgoosam/auction/dto/AuctionSearchParam.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/AuctionSearchRequestDto.java
Labels: Backend

#91 Hotfix: 결제 관련 API 수정
  sql/init_mock_data.sql
  src/main/java/com/samyookgoo/palgoosam/payment/constant/PaymentStatus.java
  src/main/java/com/samyookgoo/palgoosam/payment/constant/PaymentType.java
  src/main/java/com/samyookgoo/palgoosam/payment/controller/PaymentController.java
  src/main/java/com/samyookgoo/palgoosam/payment/controller/request/PaymentConfirmRequest.java
  src/main/java/com/samyookgoo/palgoosam/payment/controller/request/PaymentCreateRequest.java
  src/main/java/com/samyookgoo/palgoosam/payment/controller/request/PaymentFailRequest.java
  src/main/java/com/samyookgoo/palgoosam/payment/controller/request/TossPaymentConfirmRequest.java
  src/main/java/com/samyookgoo/palgoosam/payment/controller/request/TossPaymentFailCallbackRequest.java
  src/main/java/com/samyookgoo/palgoosam/payment/controller/response/OrderResponse.java
  src/main/java/com/samyookgoo/palgoosam/payment/controller/response/PaymentCreateResponse.java
  src/main/java/com/samyookgoo/palgoosam/payment/controller/response/TossPaymentConfirmResponse.java
  src/main/java/com/samyookgoo/palgoosam/payment/domain/Payment.java
  src/main/java/com/samyookgoo/palgoosam/payment/policy/DefaultDiscountPolicy.java
  src/main/java/com/samyookgoo/palgoosam/payment/policy/DeliveryPolicy.java
  src/main/java/com/samyookgoo/palgoosam/payment/repository/PaymentRepository.java
  src/main/java/com/samyookgoo/palgoosam/payment/service/PaymentService.java
Labels: Feature, Hot Fix, Refactor, Backend

#93 Feat: 경매 입찰 금액 유효성 검증 및 취소된 입찰 제외한 카운트 로직 적용
  src/main/java/com/samyookgoo/palgoosam/auction/dto/response/RelatedAuctionResponse.java
  src/main/java/com/samyookgoo/palgoosam/bid/controller/request/BidRequest.java
  src/main/java/com/samyookgoo/palgoosam/bid/repository/BidRepository.java
  src/main/java/com/samyookgoo/palgoosam/bid/service/BidService.java
Labels: Feature, Hot Fix, Backend

#90 refactor: DTO 이름 및 위치 수정, enum 클래스 constant 패키지에서 관리하도록 수정
  src/main/java/com/samyookgoo/palgoosam/auction/constant/AuctionStatus.java
  src/main/java/com/samyookgoo/palgoosam/auction/constant/ItemCondition.java
  src/main/java/com/samyookgoo/palgoosam/auction/constant/SortType.java
  src/main/java/com/samyookgoo/palgoosam/auction/controller/AuctionController.java
  src/main/java/com/samyookgoo/palgoosam/auction/domain/Auction.java
  src/main/java/com/samyookgoo/palgoosam/auction/domain/AuctionStatus.java
  src/main/java/com/samyookgoo/palgoosam/auction/domain/ItemCondition.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/AuctionListItemDto.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/AuctionSearchResultDto.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/ItemCondition.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/request/AuctionCreateRequest.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/request/AuctionSearchRequestDto.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/request/AuctionUpdateRequest.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/response/AuctionCreateResponse.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/response/AuctionDetailResponse.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/response/AuctionSearchResponseDto.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/response/AuctionUpdatePageResponse.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/response/AuctionUpdateResponse.java
  src/main/java/com/samyookgoo/palgoosam/auction/repository/AuctionRepository.java
  src/main/java/com/samyookgoo/palgoosam/auction/service/AuctionService.java
  src/main/java/com/samyookgoo/palgoosam/auction/service/dto/AuctionSearchDto.java
Labels: Refactor, Backend

#94 Feat: 카테고리 조회 API
  src/main/java/com/samyookgoo/palgoosam/auction/controller/CategoryController.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/response/CategoryResponseDto.java
  src/main/java/com/samyookgoo/palgoosam/auction/repository/CategoryRepository.java
  src/main/java/com/samyookgoo/palgoosam/auction/service/CategoryService.java
  src/main/java/com/samyookgoo/palgoosam/auth/JwtAuthenticationFilter.java
  src/main/java/com/samyookgoo/palgoosam/config/SecurityConfig.java
Labels: Feature, Backend

#100 Feat: 응답 dto 필드 정리 및 스크랩/주문페이지 응답 개선
  src/main/java/com/samyookgoo/palgoosam/auction/controller/ScrapController.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/request/AuctionCreateRequest.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/response/AuctionDetailResponse.java
  src/main/java/com/samyookgoo/palgoosam/auction/service/ScrapService.java
  src/main/java/com/samyookgoo/palgoosam/payment/controller/response/OrderResponse.java
  src/main/java/com/samyookgoo/palgoosam/payment/service/PaymentService.java
  src/main/java/com/samyookgoo/palgoosam/user/domain/Scrap.java
Labels: Feature, Backend

#99 Feat: 사용자 입찰 취소 가능 정보 추가 및 입찰 취소 조건 변경
  src/main/java/com/samyookgoo/palgoosam/bid/controller/BidController.java
  src/main/java/com/samyookgoo/palgoosam/bid/controller/response/BidListResponse.java
  src/main/java/com/samyookgoo/palgoosam/bid/repository/BidRepository.java
  src/main/java/com/samyookgoo/palgoosam/bid/service/BidService.java
Labels: Feature, Hot Fix, Backend

#103 feat: 이미지 관련 yml 파일 설정
  src/main/resources/application.yml
Labels: Feature, Backend

#97 Feat: auction search request dto에 Valid어노테이션 추가
  src/main/java/com/samyookgoo/palgoosam/auction/controller/AuctionController.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/request/AuctionSearchRequestDto.java
Labels: Feature, Backend

#101 Docs/Feat: 커스텀 어노테이션을 통해서 컨트롤러 오염도 낮추기
  src/main/java/com/samyookgoo/palgoosam/auction/api_docs/auction/AuctionCreateApi.java
  src/main/java/com/samyookgoo/palgoosam/auction/api_docs/auction/AuctionDeleteApi.java
  src/main/java/com/samyookgoo/palgoosam/auction/api_docs/auction/AuctionDetailApi.java
  src/main/java/com/samyookgoo/palgoosam/auction/api_docs/auction/AuctionSearchApi.java
  src/main/java/com/samyookgoo/palgoosam/auction/api_docs/auction/AuctionUpdateApi.java
  src/main/java/com/samyookgoo/palgoosam/auction/api_docs/auction/AuctionUpdatePageApi.java
  src/main/java/com/samyookgoo/palgoosam/auction/api_docs/auction/RelatedAuctionGetApi.java
  src/main/java/com/samyookgoo/palgoosam/auction/api_docs/scrap/AddScrapApi.java
  src/main/java/com/samyookgoo/palgoosam/auction/api_docs/scrap/RemoveScrapApi.java
  src/main/java/com/samyookgoo/palgoosam/auction/controller/AuctionController.java
  src/main/java/com/samyookgoo/palgoosam/auction/controller/ScrapController.java
  src/main/java/com/samyookgoo/palgoosam/auth/JwtAuthenticationFilter.java
  src/main/java/com/samyookgoo/palgoosam/auth/api_docs/LogoutApi.java
  src/main/java/com/samyookgoo/palgoosam/auth/api_docs/RefreshAccessTokenApi.java
  src/main/java/com/samyookgoo/palgoosam/auth/controller/AuthController.java
  src/main/java/com/samyookgoo/palgoosam/bid/api_docs/CancelBidApi.java
  src/main/java/com/samyookgoo/palgoosam/bid/api_docs/GetAuctionBidsApi.java
  src/main/java/com/samyookgoo/palgoosam/bid/api_docs/PlaceBidApi.java
  src/main/java/com/samyookgoo/palgoosam/bid/api_docs/SseSubscribeApi.java
  src/main/java/com/samyookgoo/palgoosam/bid/controller/BidController.java
  src/main/java/com/samyookgoo/palgoosam/bid/controller/SseController.java
  src/main/java/com/samyookgoo/palgoosam/config/SecurityConfig.java
  src/main/java/com/samyookgoo/palgoosam/deliveryaddress/api_docs/DeleteUserDeliveryAddressApi.java
  src/main/java/com/samyookgoo/palgoosam/deliveryaddress/api_docs/GetUserDeliveryAddressesApi.java
  src/main/java/com/samyookgoo/palgoosam/deliveryaddress/api_docs/PatchUserDefaultAddress.java
  src/main/java/com/samyookgoo/palgoosam/deliveryaddress/api_docs/PostUserDeliveryAddress.java
  src/main/java/com/samyookgoo/palgoosam/deliveryaddress/controller/DeliveryAddressController.java
  src/main/java/com/samyookgoo/palgoosam/notification/api_docs/DeleteNotificationApi.java
  src/main/java/com/samyookgoo/palgoosam/notification/api_docs/GetNotificationListApi.java
  src/main/java/com/samyookgoo/palgoosam/notification/api_docs/ReadNotificationApi.java
  src/main/java/com/samyookgoo/palgoosam/notification/api_docs/SaveFcmTokenApi.java
  src/main/java/com/samyookgoo/palgoosam/notification/controller/NotificationController.java
  src/main/java/com/samyookgoo/palgoosam/payment/api_docs/ConfirmPaymentApi.java
  src/main/java/com/samyookgoo/palgoosam/payment/api_docs/CreatePaymentApi.java
  src/main/java/com/samyookgoo/palgoosam/payment/api_docs/GetOrderPageApi.java
  src/main/java/com/samyookgoo/palgoosam/payment/api_docs/PostFailPaymentApi.java
  src/main/java/com/samyookgoo/palgoosam/payment/controller/OrderController.java
  src/main/java/com/samyookgoo/palgoosam/payment/controller/PaymentController.java
  src/main/java/com/samyookgoo/palgoosam/search/api_docs/DeleteSearchHistory.java
  src/main/java/com/samyookgoo/palgoosam/search/api_docs/GetSearchHistoryApi.java
  src/main/java/com/samyookgoo/palgoosam/search/api_docs/GetSuggestionsApi.java
  src/main/java/com/samyookgoo/palgoosam/search/api_docs/RecordUserSearchApi.java
  src/main/java/com/samyookgoo/palgoosam/search/controller/SearchHistoryController.java
  src/main/java/com/samyookgoo/palgoosam/user/api_docs/GetUserAuctionsApi.java
  src/main/java/com/samyookgoo/palgoosam/user/api_docs/GetUserBidsApi.java
  src/main/java/com/samyookgoo/palgoosam/user/api_docs/GetUserInfoApi.java
  src/main/java/com/samyookgoo/palgoosam/user/api_docs/GetUserPaymentsApi.java
  src/main/java/com/samyookgoo/palgoosam/user/api_docs/GetUserScrapsApi.java
  src/main/java/com/samyookgoo/palgoosam/user/controller/UserController.java
Labels: Docs, Feature, Backend

#102 Fix: auction service 에러 수정
  src/main/java/com/samyookgoo/palgoosam/auction/service/AuctionService.java
Labels: Bug Fix

#106 Fix: 경매 컨트롤러 import 경로 수정
  src/main/java/com/samyookgoo/palgoosam/auction/controller/AuctionController.java
Labels: Bug Fix

#109 Fix: 인증 화이트리스트 URL 적용 리팩토링
  src/main/java/com/samyookgoo/palgoosam/auth/JwtAuthenticationFilter.java
  src/main/java/com/samyookgoo/palgoosam/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: Refactor, Backend

#110 Fix: 검색 필터링이 적용되지 않던 버그 수정, 최대/최소 금액에 대한 검증 추가
  src/main/java/com/samyookgoo/palgoosam/auction/dto/request/AuctionSearchRequestDto.java
  src/main/java/com/samyookgoo/palgoosam/auction/repository/AuctionRepository.java
Labels: Bug Fix, Backend

#116 Hotfix: 입찰 취소 횟수 제한 및 판매자 입찰 금지 로직 추가
  src/main/java/com/samyookgoo/palgoosam/bid/controller/response/BidListResponse.java
  src/main/java/com/samyookgoo/palgoosam/bid/controller/response/BidResponse.java
  src/main/java/com/samyookgoo/palgoosam/bid/service/BidService.java
Labels: Hot Fix, Backend

#120 Fix: 연관 상품 목록 응답 DTO 필드명 및 구조 변경
  src/main/java/com/samyookgoo/palgoosam/auction/dto/response/RelatedAuctionResponse.java
Labels: Feature, Backend

#122 Feat: 입찰 API 응답에 canCancelBid 필드 추가
  src/main/java/com/samyookgoo/palgoosam/bid/controller/BidController.java
  src/main/java/com/samyookgoo/palgoosam/bid/controller/response/BidListResponse.java
  src/main/java/com/samyookgoo/palgoosam/bid/controller/response/BidResultResponse.java
  src/main/java/com/samyookgoo/palgoosam/bid/service/BidService.java
Labels: Feature, Backend

#124 Feat: 주문 조회 로직 개선 및 낙찰자/결제 여부 응답 필드 추가
  src/main/java/com/samyookgoo/palgoosam/auction/dto/response/AuctionDetailResponse.java
  src/main/java/com/samyookgoo/palgoosam/auction/service/AuctionService.java
  src/main/java/com/samyookgoo/palgoosam/payment/controller/OrderController.java
  src/main/java/com/samyookgoo/palgoosam/payment/repository/PaymentRepository.java
  src/main/java/com/samyookgoo/palgoosam/payment/service/OrderService.java
  src/main/java/com/samyookgoo/palgoosam/payment/service/PaymentService.java
Labels: Feature, Backend

#140 Fix: close missing brace in getRecentAuctions
  src/main/java/com/samyookgoo/palgoosam/auction/controller/HomeController.java
  src/main/java/com/samyookgoo/palgoosam/auction/service/HomeService.java
Labels: Hot Fix, Backend

#141 Fix: 경매 검색 로직 수정
  src/main/java/com/samyookgoo/palgoosam/auction/domain/AuctionSearchProjection.java
  src/main/java/com/samyookgoo/palgoosam/auction/dto/request/AuctionSearchRequestDto.java
  src/main/java/com/samyookgoo/palgoosam/auction/repository/AuctionRepository.java
  src/main/java/com/samyookgoo/palgoosam/auction/repository/AuctionSearchRepository.java
  src/main/java/com/samyookgoo/palgoosam/auction/service/AuctionService.java
  src/main/java/com/samyookgoo/palgoosam/auction/service/dto/AuctionSearchDto.java
Labels: Feature, Perf, Backend

#142 Style: Auction 도메인 사용하지 않는 코드 삭제
  src/main/java/com/samyookgoo/palgoosam/auction/controller/AuctionController.java
  src/main/java/com/samyookgoo/palgoosam/auction/service/AuctionService.java
Labels: Backend
